feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.15
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 10
img_enable : 1
lidar_enable : 1
outlier_threshold : 150 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 426.551167166986
cam_fy: 426.6142447926181
cam_cx: 429.1314081919893
cam_cy: 247.64043896840604

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1 # Livox Avia LiDAR
    scan_line: 1
    blind: 0.2 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    fov_degree:    80
    extrinsic_T: [ -0.0275814, 0.0145758, -0.085423 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /camera/color/image_raw
    #xiyuan
    Rcl: [0.0110805,-0.999823,0.0151929,
          -0.0410198,-0.0156355,-0.999036,
          0.999097,0.0104466,-0.0411858]
    Pcl: [0.0183, 0.0762623, -0.0305996]
    
